#Numpy Library in Python

###### NumPy is a Python library
###### NumPy is used for working with arrays
###### NumPy is shprt for "Numerical Python"

In [1]:
import numpy as np

Numpy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, forier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy standas for Numerical Python

# Why Use NumPy?

In Python we have lists that serve the purpose of arraus, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarrey, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

# Why is NumPy faster than lists?

NumPy are stored at one continuous place in memory unlike lists, so proceses can access and manipulate them very efficiently.

The behaviour is called lovality of reference in computer science.

this is the main reason why NumPy is faster then lists. Also it is optimized to work with latest CPU architectures.

# Which Languages is NumPy written is?

NumPy is a Python library and is written partially in Python, but most of the parts that requeire fast computation are written in C or C++.

# Create a NumPy ndarray Object

In [3]:
arr = np.array([1,2,3,4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


#Dimensions in Arrays

In [6]:
#0-D Arrays
arr0 = np.array(42)
print(arr0)
#1-D Array
arr1 = np.array([42,43])
print(arr1)
#2-D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
#3-D Array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

42
[42 43]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#Check Number of Dimensions

NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimension the array have.

In [7]:
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


# Higer Dimensional Arrays

An arrays can have any number of dimensions.

When the arrays is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


#Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by refering to its index number

The indexes in NumPy arrays star with 0, meaning that the first element has index 0, and the second has index 1 etc.

#Negative Indexing

Use negative indexing to access an array from the end

In [16]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr1[0])
print(arr1[2])
print(arr2[1][1])
print(arr2[1,2])
print(arr1[-1])
print(arr1[-2])
print(arr2[-1,-1])

1
3
6
7
6
5
8


#Slicing Arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this **[start:end]**

We can also define the step, like this **[start:end:step]**

If we don't pass start its considered zero.

If we don't pass end its considered length of array in that dimension.

If we don't pass step its considered 1.

**Note** The result includes the start index, but excludes the end index.

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[:2])
print(arr[2:5])
print(arr[4:])
print(arr[-3:-1])
print(arr[0:8:2])


[1 2]
[3 4 5]
[5 6 7 8 9]
[7 8]
[1 3 5 7]


#NumPy Data Types
## Data Types in Python
By default Python have these data types
- **strings**:
- **integer**
- **float**
- **boolean**
- **complex**

## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigened integers etc.

Bellor is a list of all data types in NumPy and the characters used to represent them.

- **i** - integer
- **b** - boolean
- **u** - unsigned integer
- **f** - float
- **c** - complex float
- **m** - timedelta
- **M** - datetime
- **O** - object
- **S** - string
- **U** - unicode string
- **V** - fixed chunk of memory for other type (void)

## Checking the Data Type of an Array

The NumPy arrays object has a property called **dtype** that returns the data type of the array;

## Creating Arrays With a Defined Data Type

We use the **array()** function to create arrayes, this fuction can take an optional argument: dtype that allows us to difine the expected type of the array elements:

#Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the **astype()** method.

The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using, like 'f'for float 'i' for integer etc, or you can use the data type directly like float for float int for integer.



In [33]:
arr = np.array([1,2,3,4])

print(arr.dtype)

arr = np.array(['apple', 'strawberry', 'orange', 'grapes'])

print(arr.dtype)

arr = np.array(['apple', 'strawberry', 'orange', 'grapes'], dtype='S')

print(arr.dtype)

arr = np.array([1.1,2.2,3.3])

print(arr.dtype)

arr = arr.astype('i')

print(arr)

int64
<U10
|S10
float64
[1 2 3]


#The Difference Between COPY and VIEW

The main difference between a copy and a view of an array is that the copy is a new arays, and the view is just a view of the original arrays.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original aray, and any changes made to the original array will affect the view.

In [36]:
arr = np.array([1,2,3,4,5,6])
#COPY
x = arr.copy()
print(x)
y = arr.view()
print(y)

x[0]=9

print(x)
print(arr)

y[0]=9

print(y)
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[9 2 3 4 5 6]
[1 2 3 4 5 6]
[9 2 3 4 5 6]
[9 2 3 4 5 6]


#Shape of an arrray

The shape of an array is the number of elements in each dimension

## Get the shape of ans Array

NumPy arrays have an attribute called **shape** that returns a tuple with index having the number of corresponding elements.

## NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By representing we can add or remove dimensions or change number of elements in each dimension.

## Flattening the arrays

Flattening array mean converting a multidimensional array into a 1D array

We can use the **reshape(-1)** to do this

In [48]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

newarr = arr.reshape(2,3,2)

print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

(2, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6]


#NumPy Array Iterating

## Iteratins Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using asic for loop of python.

If we iterate on a 1-D array it will go thorugh each element one by one.

## Iterating through 2-D Arrays

In a 2-D array it will go through all the rows.



In [53]:
arr = np.array([1,2,3,4,5,6])

for i in arr:
  print(i)

arr = np.array([[1,2,3,4],[5,6,7,8]])

for j in arr:
  for i in j:
    print(i)

1
2
3
4
5
6
1
2
3
4
5
6
7
8


## Iterating Arrays Using nditer()

The function **nditer()** is a helping function that can be used from a very advnced iterations. It solves some basics issues which we face in iteration, lets go through it with examples.



In [54]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


#NumPy Joining Arrays


## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a singles array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the **concatenate()** function, along with the axes. If axes is not explicitly passed, it is taken as 0.

In [62]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6])

newarr = np.concatenate((arr1, arr2))

print(newarr)


arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

newarr = np.concatenate((arr1, arr2), axis=1)

print(newarr)


[1 2 3 4 5 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


# NumPy Splitting Array

## Splitting NumPy Arrays

Splitting is reverse operations of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use **array_split()** for splitting arrays, we pass it the array we want to split and the number of splits.

## Splitting 2-D Arrays

use the same syntax when splitting 2-D arrays

In [72]:
arr = np.array([1,2,3,4,5,6,7])

newarr = np.array_split(arr, 3)

print(newarr)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print(arr)

newarr = np.array_split(arr,4)
print()
print(newarr[0])
print()
print(newarr[1])
print()
print(newarr[2])
print()
print(newarr[3])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 9 10]]

[[11 12]]


#NumPy Searching Arrays

## Searching Arrays

You can search an array for certaing value, and return the indexes that get a match.

To seach an array, we use the where() method.

In [74]:
x = np.array([1,2,3,4,5,6,4,4,5,8,9,4,4,8,9,7,5,6,4,5])

newx = np.where(x==4) #Retorna uma array com os índices onde possuem o valor 4

print(newx)

(array([ 3,  6,  7, 11, 12, 18]),)


#NumPy Sorting Arrays

## Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corrresponding to elements, like numeric or alphabetical, ascending or descending .

The NumPy ndarray object has a function called **sort()**, that will sort a specified array.

**Note:** This method returns a copy of the array, leaving the original array unchanged.

## Sorting 2-D Arrays

if you use the sort() method on a 2-D array, both arrays will be sorted.


In [77]:
arr = np.array([3,2,0,1])

print(np.sort(arr))

arr = np.array([ 'passionfruit', 'banana', 'apple' , 'grapes'])

print(np.sort(arr))

arr = np.array([[4,1,8,9],[4,8,2,9]])

print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'grapes' 'passionfruit']
[[1 4 8 9]
 [2 4 8 9]]


# NumPy Filter Array

## Filtering Arrays

Getting some elements out of an existing arrays and creating a new array out of them is called filtering.

In NumPy, you can filter an array using a boolean index list.

In [80]:
arr = np.array([42,43,44,45])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

arr = np.array([1,2,3,4,5,6,7])

filter_arr = arr % 2 == 0

print(filter_arr)

SyntaxError: invalid syntax (<ipython-input-80-0cb2f6a6b830>, line 11)